### ISSUE TITLE
ListBox multiple selection (mobile friendly)

### ISSUE THREAD

**Issue by ghost** [RowellKataan/Unity-List-Box#2]
Hi, its me again :)

Only a question: Is it possible to make multiple selection works without the needing of pressing CTRL?

I'm developing for a mobile app and it would be nice.

The approach i have thought is making the list permorms allways as if ctrl was pressed if a editor checkbox is selected (i.e. mobile friendly multiple selection)

Thanks for your time.

**Comment by RowellKataan** [comment]
I've not done too much mobile programming  (actually, I haven't really done any).

What sort of state would you use to detect a regular tap versus a "Control-Tap" to differentiate between a "I only want to select one item" from "I want to select this item, and that item, and that other item"?

I suppose I could add a flag to the ListBox control that removes the "Control key" feature, and automatically detects all selections as a toggle (as if the control key were being pressed).  Would that option work?

**Comment by RowellKataan** [comment]
Done.   Added a switch to allow the List Items to be toggled Selected/Unselected, as if the Control key were always being pressed.  Update published moments ago.
