### ISSUE TITLE
Adding Items to dropdown from code.

### ISSUE THREAD

**Issue by ghost** [RowellKataan/Unity-List-Box#3]
Hello mate,

First of all, thanks for the job with the mobile friendly multiple selection thing. Great job :)

Im having an issue with the DropdownListControl:
- When i try to refer from code to the DropdownListControl component of the dropdown gameobject it returns null. It is normal since it havent any component called dropdownlistcontrol. It has one called "Dropdown", but i cant refer it from code.

- Im doing the same with the combobox, and im having no problem with it.

Thanks for your time :)
Best regards.

**Comment by RowellKataan** [comment]
You should be able to grab the component off of your gameobject using something like:

```
DropDownListControl ddl = myGameObject.GetComponent<DropDownListControl>();
ListBoxControl lb = myOtherGameObject.GetComponent<ListBoxControl>();
```


The "Dropdown" is Unity's built-in UI object.

If you look in the Demo scene, look for the "DropDown Prefab", inside the "Demo DropDown Panel".  That should serve as an example how the drop down list object is added/used in the scene.

Hope this helps.

**Comment by ghost** [comment]
Ok, i wasn't using your prefab, but the Unity dropdown. Sorry.

Yes, you helped me a lot. :)

Closing the issue.
