### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by ghost** [RowellKataan/Unity-List-Box#4]
Hello mate.

I found this lines inside ListBoxControl.Start (line 367)

```
// RESIZE THE ITEM CONTAINER TO THE WIDTH OF THE SCROLL RECT
	if (ContainerRect != null)               
                ContainerRect.sizeDelta = new Vector2(ScrollRect.rect.width, ScrollRect.rect.height);
```

You are resizing also the height.

Suddenly, i noticed that my combobox wasn't scrolling properly. I say suddenly, because it was doing well untill 10 minutes ago.

I switched

 ` ContainerRect.sizeDelta = new Vector2(ScrollRect.rect.width, ScrollRect.rect.height);`

with

  `ContainerRect.sizeDelta = new Vector2(ScrollRect.rect.width, ContainerRect.rect.height);`

and it is working fine.

Maybe I'm wrong, but maybe i found a bug :)

Best regards

**Comment by RowellKataan** [comment]
Good find!  Thanks.
