### ISSUE TITLE
Can I customize the ListBox Item text somehow ?

### ISSUE THREAD

**Issue by StavrosDimou** [RowellKataan/Unity-List-Box#5]
Hello, and thank you very much for this package.
I was wondering if there is a way I can costumize the way the text appears for each item of the ListBox ?
Like choose the font size and family ?
I want to use it on something that will run at Windows PCs, and the default text gets too blurry at PC resolutions unfortunately, because it uses smaller font size stretched up instead of using a larger one.

**Comment by RowellKataan** [comment]
You can absolutely change the font in the list box.   You can modify the "ListBox Line Item Prefab" and change the font in the "Line Item Main Text"  and "Line Item Sub Text"  UI text fields to whatever you'd like.
